import pygame


HEIGHT = 640
WIDTH = 1280

HEIGHT_WIDTH_RATIO = HEIGHT / WIDTH

NUMBER_OF_PIXELS_X = 40
NUMBER_OF_PIXELS_Y = int(NUMBER_OF_PIXELS_X * HEIGHT_WIDTH_RATIO)

PIXEL_LENGTH = WIDTH / NUMBER_OF_PIXELS_X

FPS = 60

screen = pygame.display.set_mode((WIDTH, HEIGHT))
